---
abstract: 'A Perl HTML pretty printer to use with Google prettify CSS skins, no JavaScript required!'
author:
  - 'David Farrell <sillymoos@cpan.org> L<PerlTricks.com|http://perltricks.com>'
build_requires:
  Data::Dumper: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.010, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PPI-Prettify
requires:
  Carp: 0
  Exporter: 0
  PPI::Document: 0
  base: 0
  strict: 0
  warnings: 0
version: 0.02
